// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO1TnrNlOAuviSU0-Jg8jfz5dM9ZOiHBE',
    appId: '1:196026462572:web:c94dd8b3e7eaa1f1cec349',
    messagingSenderId: '196026462572',
    projectId: 'hola-tp-firebase',
    authDomain: 'hola-tp-firebase.firebaseapp.com',
    storageBucket: 'hola-tp-firebase.firebasestorage.app',
    measurementId: 'G-VD8L2CELDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbl9Q9JlEE5qIpZHxbwVADGe2eLxvI85I',
    appId: '1:196026462572:android:ce1a019a083bdd15cec349',
    messagingSenderId: '196026462572',
    projectId: 'hola-tp-firebase',
    storageBucket: 'hola-tp-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL1hxig9RSsJP_oENfX_wsuCH8nKmnBbI',
    appId: '1:196026462572:ios:fb200d90355733afcec349',
    messagingSenderId: '196026462572',
    projectId: 'hola-tp-firebase',
    storageBucket: 'hola-tp-firebase.firebasestorage.app',
    iosBundleId: 'com.example.loginhome1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL1hxig9RSsJP_oENfX_wsuCH8nKmnBbI',
    appId: '1:196026462572:ios:fb200d90355733afcec349',
    messagingSenderId: '196026462572',
    projectId: 'hola-tp-firebase',
    storageBucket: 'hola-tp-firebase.firebasestorage.app',
    iosBundleId: 'com.example.loginhome1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAO1TnrNlOAuviSU0-Jg8jfz5dM9ZOiHBE',
    appId: '1:196026462572:web:8eaf2a7db98b349fcec349',
    messagingSenderId: '196026462572',
    projectId: 'hola-tp-firebase',
    authDomain: 'hola-tp-firebase.firebaseapp.com',
    storageBucket: 'hola-tp-firebase.firebasestorage.app',
    measurementId: 'G-K1TF52XRH6',
  );
}
