// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy2-KzWC9yTPlgPhOSfIsDTWAQErP6nwY',
    appId: '1:564761320811:web:9dcd971d0fb07dac46802e',
    messagingSenderId: '564761320811',
    projectId: 'neoposture-f7e7f',
    authDomain: 'neoposture-f7e7f.firebaseapp.com',
    storageBucket: 'neoposture-f7e7f.firebasestorage.app',
    measurementId: 'G-06G28CG5B3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz-VyZZ-JG6mEHdvwSguV___D8ms-gwFs',
    appId: '1:564761320811:android:cfebf2f07d39ae0946802e',
    messagingSenderId: '564761320811',
    projectId: 'neoposture-f7e7f',
    storageBucket: 'neoposture-f7e7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsNusLgy8ca9xdcpgj7WmoXcr_YGMtI54',
    appId: '1:564761320811:ios:51dd7ae6e1f6ae6c46802e',
    messagingSenderId: '564761320811',
    projectId: 'neoposture-f7e7f',
    storageBucket: 'neoposture-f7e7f.firebasestorage.app',
    iosBundleId: 'com.example.neoposture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsNusLgy8ca9xdcpgj7WmoXcr_YGMtI54',
    appId: '1:564761320811:ios:51dd7ae6e1f6ae6c46802e',
    messagingSenderId: '564761320811',
    projectId: 'neoposture-f7e7f',
    storageBucket: 'neoposture-f7e7f.firebasestorage.app',
    iosBundleId: 'com.example.neoposture',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDy2-KzWC9yTPlgPhOSfIsDTWAQErP6nwY',
    appId: '1:564761320811:web:85d25f9f9a34172746802e',
    messagingSenderId: '564761320811',
    projectId: 'neoposture-f7e7f',
    authDomain: 'neoposture-f7e7f.firebaseapp.com',
    storageBucket: 'neoposture-f7e7f.firebasestorage.app',
    measurementId: 'G-TP8VGBQ6BX',
  );
}
