name: neoposture
description: "Mecaproyecto"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.35.5
  flutter_riverpod: ^2.6.1
  permission_handler: ^11.3.1
  go_router: ^15.1.2
  flutter_local_notifications: ^19.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true